<a href="https://colab.research.google.com/github/niwanulgiffar/MBKM/blob/main/Kampus_Merdeka_Muhamad_Niwanul_Giffar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Muhamad Niwanul Giffar (5551917)

Pada tugas ini selain beberapa sel koding yang sudah ada, saya membuat versi modifikasi pada sel koding baru (misal dengan mengganti jenis loopingnya dan modifikasi lainnya). Saya juga menambahkan koding baru seperti operasi matriks, uji hipotesis, operasi string, dan lain-lain.

In [1]:
odd=[x for x in range(1,100+1) if x %2!=0] #membuat list bilangan ganjil dari 1 sampai 100
squares=[x**2 for x in odd]
total=sum(squares)
ratarata=total/len(squares)
print(total)
print(ratarata)

166650
3333.0


In [5]:
even=[x for x in range(1,100+1) if x %2==0] #membuat list bilangan genap dari 1 sampai 100
squares=[x**2 for x in even]
total=sum(squares)
mean=total/len(squares)
print(total)
print(mean)

171700
3434.0


In [6]:
a = int(input("masukan a= "))
if a<60: #conditional form
    print('small value')
else:
    print('big value')

masukan a= 59
small value


In [7]:
a =  7
b = 8
c = 5

perhitungan = (a+b)/c
print("Hasil perhitungan :", perhitungan)
if perhitungan < 10:
  print("small value")
else:
  print("Big value")



Hasil perhitungan : 3.0
small value


In [10]:
#Perhitungan sederhana dengan if else
a = float(input())
b = float(input())
operator = input("")  # operator yang ingin digunakan (+, -, *, /)

if operator == "+":
    result = a + b
    print("Hasil penjumlahan:", result)
elif operator == "-":
    result = a - b
    print("Hasil pengurangan:", result)
elif operator == "*":
    result = a * b
    print("Hasil perkalian:", result)
elif operator == "/":
    if b != 0:
        result = a / b
        print("Hasil pembagian:", result)
    else:
        print("Error: Pembagian oleh nol tidak diizinkan")
else:
    print("Operator tidak valid")


7
2
*
Hasil perkalian: 14.0


In [11]:
##if else untuk statistika sederhana (mean dan std deviasi)
import math #untuk sqrt

data = [50,56,61,65,70]
count = len(data)
total = sum(data)
mean = total / count
diff_squares = [(x - mean) ** 2 for x in data]
sum_diff_squares = sum(diff_squares)
variance = sum_diff_squares / count
standard_deviation = math.sqrt(variance)

if count > 0:
    print("Jumlah data:", count)
    print("Total data:", total)
    print("Rata-rata data:", mean)
    print("Standar deviasi:", standard_deviation)
else:
    print("Tidak ada data yang tersedia.")

Jumlah data: 5
Total data: 302
Rata-rata data: 60.4
Standar deviasi: 6.945502141674135


In [12]:
#python uji t sederhana
import numpy as np
from scipy.stats import ttest_ind

group1 = np.array([7,6,5,8,9])
group2 = np.array([11,10,8,9,7])


t_statistic, p_value = ttest_ind(group1, group2) #t-test independent

print("T-Statistic:", t_statistic)
print("P-Value:", p_value)

if p_value < 0.05: #untuk lihat H0 ditolak atau gagal ditolak pada taraf signifikansi 5 persen
  print("H0 ditolak")
else:
  print("H0 Gagal ditolak")

T-Statistic: -2.0
P-Value: 0.08051623795726257
H0 Gagal ditolak


In [13]:
while True:
  a = int(input("masukan a= "))
  if a<60:
    print('small value')
  else:
    print('big value')
    break

masukan a= 61
big value


In [ ]:
pas= input("password= ")
panjang=len(pas)>=5
c8="8" in pas
cx= "X" in pas
char="@" in pas
if panjang!=True:
    print("terlalu pendek")
elif c8!=True:
    print("harus mengandung 8")
elif cx!=True:
    print("harus mengandng X")
elif char!=True:
    print("harus mengandng @")
else:
    print("password valid")

password= kampusX@8
password valid


In [ ]:
while True:
    pas= input("password= ")
    panjang=len(pas)>=5
    c8="6" in pas
    cx= "X" in pas
    char="@" in pas
    if panjang!=True:
        print("terlalu pendek")
    elif c8!=True:
        print("harus mengandung 8")
    elif cx!=True:
        print("harus mengandng X")
    elif char!=True:
        print("harus mengandng @")
    else:
        print("password valid")
        break

password= kampusX@8
password valid


In [14]:
#password 4 kali percobaan dengan looping for 
valid = False #nilai awal valid adalah false untuk melihat apa password yang diinput valid atau tidak

for _ in range(4): 
    pas = input("password= ")
    panjang = len(pas) >= 5
    c8 = "8" in pas
    cx = "X" in pas
    char = "@" in pas
    
    if not panjang:
        print("Terlalu pendek")
    elif not c8:
        print("Harus mengandung 8")
    elif not cx:
        print("Harus mengandung X")
    elif not char:
        print("Harus mengandung @")
    else:
        print("Password valid")
        valid = True
        break

if not valid:
    print("Batas percobaan telah mencapai batas maksimal")

password= 4a7
Terlalu pendek
password= 681sh
Harus mengandung X
password= 7hsso
Harus mengandung 8
password= 3a8
Terlalu pendek
Batas percobaan telah mencapai batas maksimal


In [16]:
count=0
contoh_list=['acc', 'xyz', 'aba', '1221']
for i in range(len(contoh_list)):
    if(contoh_list[i][0] == contoh_list[i][-1]): #artinya jika karakter pertama dan karakter terakhir sama
        count += 1
print('jumlah string yg sama=',count)

jumlah string yg sama= 2


In [ ]:
while True:
    kata=input("masukan kata= ")
    if kata == kata[::-1]:
        print("string merupakan palidrom")
        break
    else:
        print("string bukan palidrom")

masukan kata= sayur
string bukan palidrom
masukan kata= ini
string merupakan palidrom


In [17]:
#Fungsi hitung string dengan looping for
def count_string(string):
    count = 0
    for karakter in string:
        count += 1
    return count

string_input = input("")
panjang = count_string(string_input)
print("Jumlah huruf:", panjang)

aku
Jumlah huruf: 3


In [18]:
def hitung(s):
    d={'upper':0,'lower':0}
    for x in s:
        if x.isupper():
            d['upper']+=1
        elif x.islower():
            d['lower']+=1
    print('string kalimat:', s)
    print('jumlah huruf kapital:',d['upper'])
    print('jumlah huruf kecil',d['lower'])
hitung('aAsssSWWWJHSJ')

string kalimat: aAsssSWWWJHSJ
jumlah huruf kapital: 9
jumlah huruf kecil 4


In [23]:
def ubah_ke_kapital(text, title=False):
    if title:
        return text.title()
    else:
        return text.upper()

pilihan = input("Pilih upper atau title: ")
string = input("Masukkan string: ")

if pilihan == "title":
    hasil = ubah_ke_kapital(string, title=True)
    print("Hasil :", hasil)
elif pilihan == "upper":
    hasil = ubah_ke_kapital(string)
    print("Hasil :", hasil)
else:
    print("Pilihan tidak valid. Pilih upper atau title.")


Pilih upper atau title: title
Masukkan string: joko pinurbo 
Hasil : Joko Pinurbo 


In [27]:
#kode menghitung huruf kapital tapi loopingnya diubah jadi while dan stringnya diinputkan sendiri
def hitung(s):
    d = {'upper': 0, 'lower': 0}
    index = 0
    while index < len(s):
        if s[index].isupper():
            d['upper'] += 1
        elif s[index].islower():
            d['lower'] += 1
        index += 1
    return d

input_string = input("")
result = hitung(input_string)

print('string kalimat:', input_string)
print('jumlah huruf kapital:', result['upper'])
print('jumlah huruf kecil:', result['lower'])

KaHliLGibraN
string kalimat: KaHliLGibraN
jumlah huruf kapital: 5
jumlah huruf kecil: 7


In [28]:
#Kata ganjil
list1=["ada","sapa","warga","kanopi","layang","tamu","kampus"]
for i in list1:
    if len(i)%2==1:
        print(i,end=" ")

ada warga 

In [29]:
#kata ganjil dengan while
list1 = ["ada", "sapa", "warga", "kanopi", "layang", "tamu", "kampus"]
index = 0

while index < len(list1):
    if len(list1[index]) % 2 == 1:
        print(list1[index], end=" ")
    index += 1

ada warga 

In [30]:
#kata genap
list1=["ada","sapa","warga","kanopi","layang","tamu"]
for i in list1:
    if len(i)%2==0:
        print(i,end=" ")

sapa kanopi layang tamu 

In [31]:
#kata genap dengan while
list1 = ["ada", "sapa", "warga", "kanopi", "layang", "tamu"]
index = 0

while index < len(list1):
    if len(list1[index]) % 2 == 0:
        print(list1[index], end=" ")
    index += 1

sapa kanopi layang tamu 

In [32]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print("Matriks A")
print(A)
print("\n")

B = np.array([[5, 6], [7, 8]])
print("Matriks B")
print(B)
print("\n")

C = A + B # Penjumlahan matriks A dan B
print("Penjumlahan A + B:")
print(C)
print("\n")

D = A - B # Pengurangan matriks A dan B
print("Pengurangan A - B:")
print(D)
print("\n")

E = np.matmul(A, B) # Perkalian matriks A dan B
print("Perkalian A * B:")
print(E)
print("\n")

F = np.transpose(A) # Transpose matriks A
print("Transpose A:")
print(F)
print("\n")

G = np.linalg.inv(A)# Invers matriks A
print("Invers A:")
print(G)
print("\n")

det_A = np.linalg.det(A) # Determinan matriks A
print("Determinan A:", det_A)
print("\n")

Matriks A
[[1 2]
 [3 4]]


Matriks B
[[5 6]
 [7 8]]


Penjumlahan A + B:
[[ 6  8]
 [10 12]]


Pengurangan A - B:
[[-4 -4]
 [-4 -4]]


Perkalian A * B:
[[19 22]
 [43 50]]


Transpose A:
[[1 3]
 [2 4]]


Invers A:
[[-2.   1. ]
 [ 1.5 -0.5]]


Determinan A: -2.0000000000000004


